namevote/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('open_choice_polls.urls')),

    # https://docs.djangoproject.com/en/3.0/ref/contrib/admin/admindocs/
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    path('admin/', admin.site.urls),
]

open_choice_polls/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'open_choice_polls'
urlpatterns = [
    path('', views.QuestionListView.as_view(), name='question-list'),

    path('voter/password_change/', auth_views.PasswordChangeView.as_view(), name='password-change'),
    path('voter/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password-change-done'),
    path('voter/password_reset/', auth_views.PasswordResetView.as_view(), name='password-reset'),
    path('voter/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('voter/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('voter/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password-reset-complete'),

    path('voter/enroll/', views.EnrollFormView.as_view(), name='voter-enroll'),
    path('voter/logout/', auth_views.LogoutView.as_view(), name='voter-logout'),
    path('voter/sign_in/', views.SignInFormView.as_view(), name='voter-sign-in'),

    # leave as last as it potentially shadows the other voter/ path
    path('voter/<username>/', views.VoterDetailView.as_view(), name='voter-detail'),

    path('<slug:slug>,<uuid:id>/', views.QuestionDetailView.as_view(), name='question-detail'),
    path('<slug:slug>,<uuid:id>/vote/', views.QuestionEnterVoteView.as_view(), name='vote'),
    path('<slug:slug>,<uuid:id>/choices/', views.QuestionAddChoiceView.as_view(), name='choices'),
    path('<slug:slug>,<uuid:id>/results/', views.QuestionResultsView.as_view(), name='results'),
]

open_choice_polls/models.py
import random
import re
import uuid
from datetime import timedelta

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models, IntegrityError
from django.db.models import Q
from django.db.models.functions import Lower
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from open_choice_polls import settings

SELECTED_LETTERS = 'ABCDEFGHKMNPQRSTUVWX'
SELECTED_NUMBERS = '23456789'


class ActiveVoterManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(is_voter=True) & Q(is_enrolled=True))


class Voter(models.Model):
    # DATABASE FIELDS
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    is_voter = models.BooleanField(default=False, editable=False,
                                   verbose_name=_('Is Voter?'))
    is_enrolled = models.BooleanField(default=False, editable=True,
                                      verbose_name=_('Is Enrolled?'))

    enrollment_code = models.CharField(max_length=80, blank=True, editable=False,
                                       verbose_name=_('Enrollment Code'))

    enrollment_code_is_distributed = models.BooleanField(default=False, editable=True,
                                                         verbose_name=_('Is Distributed?'))

    enrollment_code_valid_until = models.DateTimeField(verbose_name=_('Enrollment Code valid until'),
                                                       blank=True, null=True,
                                                       help_text=_("Leave empty for codes that never expire"))

    # MANAGERS
    objects = models.Manager()  # default
    active = ActiveVoterManager()

    # META CLASS
    class Meta:
        ordering = ('user',)

    # REPR and TO STRING METHOD
    def __repr__(self):
        return "<{0}: {1}>".format(
            self.__class__.__name__,
            self.user.username)

    def __str__(self):
        return self.user.username

    # ABSOLUTE URL METHOD
    def get_absolute_url(self):
        return reverse('open_choice_polls:voter-detail', kwargs={'username': self.user})

    @staticmethod
    def create_enrollment_code():
        first = get_random_string(5, SELECTED_LETTERS)
        second = get_random_string(4, SELECTED_NUMBERS)
        third = get_random_string(5, SELECTED_LETTERS.lower())
        return "{}-{}-{}".format(first, second, third)

    @staticmethod
    def create_new_password():
        first = get_random_string(4, SELECTED_LETTERS)
        second = get_random_string(3, SELECTED_NUMBERS)
        third = get_random_string(4, SELECTED_LETTERS.lower())
        return "{}-{}-{}".format(first, second, third)

    @classmethod
    def create_voter(cls, amount=1, code_valid_timedelta_days=None, question_id=None):
        """ creates **upto** `amount` voters - duplicate random ids will not create a new voter"""
        if amount < 1:
            raise NotImplementedError("create at least 1 Voter!")

        prefix = settings.OPEN_CHOICE_POLLS_VOTER_PREFIX

        ids_rand = random.sample(range(settings.OPEN_CHOICE_POLLS_VOTER_RANGE_START,
                                       settings.OPEN_CHOICE_POLLS_VOTER_RANGE_END), amount)

        res = []
        for i in ids_rand:
            # Create user and save to the database
            voter_username = '{}{}'.format(prefix, str(i).zfill(3))
            try:
                enrollment_code = Voter.create_enrollment_code()
                user = User.objects.create_user(voter_username, password=enrollment_code)

                user.voter.is_voter = True
                user.voter.enrollment_code = enrollment_code
                if code_valid_timedelta_days:
                    user.voter.enrollment_code_valid_until = timezone.now() + timedelta(days=code_valid_timedelta_days)

                if question_id:
                    try:
                        question = Question.objects.get(pk=question_id)
                        user.voter.participation_set.create(voter=user.voter, question=question, is_allowed=True)
                    except Question.DoesNotExist:
                        pass
                user.save()

                res.append(user)
            except IntegrityError:
                break
        return res


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Voter.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    try:
        instance.voter.save()
    except Voter.DoesNotExist:
        pass


@receiver(post_delete, sender=Voter)
def post_delete_user(sender, instance, *args, **kwargs):
    if instance.user:  # just in case user is not specified
        instance.user.delete()


class Question(models.Model):
    # DATABASE FIELDS
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # incrementing unique numeric identifier (e.g. used for "Q034...")
    number = models.IntegerField(default=0, editable=False)

    text = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, editable=False)

    choice_validation_regex = models.CharField(max_length=200, blank=True)
    choice_validation_hint = models.CharField(max_length=200, blank=True)

    description = models.TextField(verbose_name=_('Description (with basic markdown support)'), blank=True)

    created = models.DateTimeField(verbose_name=_('date created'), auto_now_add=True)

    collection_start_date = models.DateTimeField(verbose_name=_('Start Collection Phase'),
                                                 blank=True, default=timezone.now)
    collection_end_date = models.DateTimeField(verbose_name=_('End Collection Phase'),
                                               blank=True, default=timezone.now)

    voting_start_date = models.DateTimeField(verbose_name=_('Start Voting Phase'),
                                             blank=True, default=timezone.now)
    voting_end_date = models.DateTimeField(verbose_name=_('End Voting Phase'),
                                           blank=True, default=timezone.now)

    is_visible = models.BooleanField(verbose_name=_('is visible'), default=True)

    show_choices_approved = models.BooleanField(verbose_name=_('show approved choices'), default=True)
    show_choices_open = models.BooleanField(verbose_name=_('show unchecked choices'), default=True)
    show_choices_rejected = models.BooleanField(verbose_name=_('show rejected choices'), default=True)

    show_voting_results = models.BooleanField(verbose_name=_('show voting results before vote ends'), default=True)

    votes_per_session = models.PositiveSmallIntegerField(verbose_name=_('number of votes allowed '
                                                                        'per (cookie-based session)'), default=5)

    voter_participation = models.ManyToManyField(Voter, through='Participation')

    # MANAGERS
    objects = models.Manager()  # default

    # META CLASS
    class Meta:
        ordering = ('-created',)
        get_latest_by = 'created'

    # REPR and TO STRING METHOD
    def __repr__(self):
        return "<{0}: {1}>".format(
            self.__class__.__name__,
            self.number_text)

    def __str__(self):
        return self.number_text

    # SAVE METHOD
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.text)

        # This means that the model isn't saved to the database yet
        if self._state.adding:
            # Get the maximum display_id value from the database
            last_number = Question.objects.all().aggregate(largest=models.Max('number'))['largest']
            if last_number is None:
                last_number = 0

            # aggregate can return None! Check it first.
            # If it isn't none, just use the last ID specified (which should be the greatest) and add one to it
            if last_number is not None:
                self.number = last_number + 1

        super().save(*args, **kwargs)

    # ABSOLUTE URL METHOD
    def get_absolute_url(self):
        return reverse('open_choice_polls:question-detail', kwargs={'slug': self.slug, 'id': self.id})

    def clean(self):
        if self.choice_validation_regex:
            try:
                re.compile(self.choice_validation_regex)
            except re.error:
                raise ValidationError("invalid regex for choice validation")

    def collection_is_active(self):
        now = timezone.now()
        try:
            return self.collection_start_date <= now <= self.collection_end_date
        except TypeError:
            return False

    collection_is_active.boolean = True
    collection_is_active.short_description = _('Collection is active?')

    def collection_is_in_past(self):
        now = timezone.now()
        return self.collection_start_date < now and self.collection_end_date < now

    collection_is_in_past.boolean = True
    collection_is_in_past.short_description = _('Collection is in past?')

    def collection_is_in_future(self):
        now = timezone.now()
        return now < self.collection_start_date and now < self.collection_end_date

    collection_is_in_future.boolean = True
    collection_is_in_future.short_description = _('Collection is in future?')

    def collection_duration(self):
        return self.collection_end_date - self.collection_start_date

    collection_duration.short_description = _('Collection duration')

    def voting_is_active(self):
        now = timezone.now()
        try:

open_choice_polls/forms.py
import re
from django import forms
from django.core.exceptions import MultipleObjectsReturned
from django.utils.translation import gettext_lazy as _

from .models import Choice, Question


class SignInForm(forms.Form):
    username = forms.CharField(label=_("Username"), label_suffix="", required=True, max_length=100)
    password = forms.CharField(label=_("Password"), label_suffix="", strip=False)
    next = forms.CharField(required=False, widget=forms.HiddenInput())


class EnrollForm(forms.Form):
    enrollment_code = forms.CharField(label=_("Code"), label_suffix="")
    next = forms.CharField(required=False, widget=forms.HiddenInput())

    def clean_enrollment_code(self):
        # the hyphens are optional - so both will work: PDPGN-8922-fnkcg and PDPGN8922fnkcg
        data = self.cleaned_data['enrollment_code']
        data_no_hyphen = data.replace('-', '')
        return "{}-{}-{}".format(data_no_hyphen[0:5],  # PDPGN
                                 data_no_hyphen[5:9],  # 8922
                                 data_no_hyphen[9:14])  # fnkcg


class ChoiceForm(forms.ModelForm):
    choice_text = forms.CharField(required=True, max_length=100, label=False,
                                  widget=forms.TextInput(
                                      attrs={'placeholder': 'Enter Suggestion',
                                             'class': 'form-control',
                                             'autofocus': 'autofocus'}))

    class Meta:
        model = Choice
        fields = ['choice_text']

    def clean_choice_text(self):
        # remove duplicate spaces and strip space from start and end
        data = self.cleaned_data['choice_text']
        return re.sub(' +', ' ', data.strip())

    def clean(self):
        cleaned_data = super().clean()
        clean_choice_text = cleaned_data['choice_text']

        # check regex
        if self.instance.choice_validation_regex and \
                not re.compile(self.instance.choice_validation_regex).search(clean_choice_text):
            raise forms.ValidationError("Failed Regex. Hint: {}".format(self.instance.choice_validation_hint))

        # check duplicates
        try:
            self.instance.choice_set.get(choice_text=clean_choice_text)
            raise forms.ValidationError("Suggestion exists already - "
                                        "try something else: {}".format(clean_choice_text))
        except MultipleObjectsReturned:
            raise forms.ValidationError("Suggestion exists already (multiple times) - "
                                        "try something else: {}".format(clean_choice_text))
        except Choice.DoesNotExist:
            pass  # all good

        return cleaned_data


class ChoiceReviewForm(forms.ModelForm):
    class Meta:
        model = Choice

        fields = ['question', 'choice_text', 'review_status', 'review_remark']

    review_status = forms.ChoiceField(
        label='Review',
        choices=Choice.REVIEW_STATUS_CHOICES,
        initial=Choice.OPEN,
        widget=forms.RadioSelect,
    )


class VoteForm(forms.ModelForm):
    choice = forms.UUIDField(label=_("Choice"), label_suffix="", required=True)

    class Meta:
        model = Question
        fields = ['choice']

    def clean(self):
        cleaned_data = super().clean()
        clean_choice = cleaned_data['choice']

        # make sure this Choice exists for this Question
        try:
            self.instance.choice_set.get(pk=clean_choice)
        except Choice.DoesNotExist as err:
            raise forms.ValidationError("Not found: {} - {}".format(clean_choice, err))

        return cleaned_data

open_choice_polls/templates/open_choice_polls/401.html
{% extends "open_choice_polls/base.html" %}

{% load i18n %}

{% block title %}
    {# Translators: Title on 401 Page #}
    {% trans "401 Authentication Required - Vote" as title %}
    {{ title }}
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                <div class="card border-secondary mb-3">
                    <div class="card-header text-white bg-dark">
                        {% trans "401 Authentication Required" %}
                    </div>
                    <div class="card-body">
                        <p>{% trans "Access to site is restricted to internal network." %}</p>
                        <p>{% trans "Your IP Address" %}: <strong>{{ request.META.REMOTE_ADDR }}</strong></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

open_choice_polls/templates/open_choice_polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'open_choice_polls/css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'open_choice_polls/css/brands.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'open_choice_polls/css/solid.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'open_choice_polls/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'open_choice_polls/css/style.css' %}">

    <!-- CSS block per template page -->
    {% block css %}
    {% endblock %}

</head>
<body>

{% load i18n %}

<!-- Navbar https://code.luasoftware.com/tutorials/bootstrap/bootstrap-4-navbar-toggle-without-javascript/ -->
<nav class="navbar navbar-expand-md navbar-light bg-light">

    <a class="navbar-brand" href="/"><i class="fas fa-person-booth"></i> Anon Vote</a>

    <input type="checkbox" id="css-navbar-toggler" class="d-none"/>
    <label for="css-navbar-toggler" class="navbar-toggler" data-toggle="collapse" data-target="#css-navbar-content"
           aria-controls="css-navbar-content" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon ml-auto"></span>
    </label>

    <div class="navbar-collapse collapse w-100 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">
                            <i class="fas fa-cog"></i> Administration</a></li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'open_choice_polls:voter-detail' username=user.get_username %}">
                        <i class="fas fa-user-circle"></i> {{ user.get_username }}</a></li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'open_choice_polls:voter-logout' %}">
                        <i class="fas fa-sign-out-alt"></i> Sign out</a></li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'open_choice_polls:voter-enroll' %}">
                        <i class="fas fa-user-edit"></i> Enroll / Sign In</a></li>
            {% endif %}

        </ul>
    </div>
</nav>

<div class="container-fluid">

    {% include "open_choice_polls/messages_snippet.html" %}

    {% block content %}{% endblock %}
</div>

<!-- JavaScript block per template page -->
{% block js %}
{% endblock %}

</body>
</html>

open_choice_polls/templates/open_choice_polls/voter_enroll.html
{% extends "open_choice_polls/base.html" %}
{% load i18n static %}

{% block title %}
    {# Translators: Title on Enroll In Page #}
    {% trans "Enroll" as title %}
    {{ title }}
{% endblock %}

{% block content %}

    <div class="container">

        {#       START Error#}
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col">
                    <div class="card border-dark mb-3">
                        <div class="card-body">
                            <p class="text-danger">
                                You are authenticated as <strong>{{ user.get_username }}</strong>, but are not
                                authorized
                                to access this page. Would you like to login to a different account?
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        {% if form.errors or form.non_field_errors %}
            <div class="row">
                <div class="col">
                    <div class="card border-secondary mb-3">

                        <div class="card-body">

                            Errors (if any..) #TODO

                            {% if form.errors and not form.non_field_errors %}
                                <p class="errornote">
                                    {% if form.errors.items|length == 1 %}
                                        {% trans "Please correct the error below." %}{% else %}
                                        {% trans "Please correct the errors below." %}{% endif %}
                                </p>
                                {#                            {{ form.errors }}#}
                            {% endif %}

                            {% if form.non_field_errors %}
                                {% for error in form.non_field_errors %}
                                    <p class="errornote">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        {#       END Error#}

        <div class="row">
            <div class="col">

                <div class="card border-dark mb-3">

                    <div class="card-header bg-warning">
                        <h5>Enroll</h5>
                    </div>

                    <div class="card-body">

                        <form action="{% url 'open_choice_polls:voter-enroll' %}" method="post" id="login-form">
                            {% csrf_token %}

                            <div class="form-group row">
                                <label for="id_enrollment_code"
                                       class="col-sm-3 col-form-label">{{ form.enrollment_code.label }}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" required id="id_enrollment_code"
                                           placeholder="e.g. ABCDE-2345-abcde" autofocus
                                           name="enrollment_code"
                                            {% if form.enrollment_code.value %}
                                           value="{{ form.enrollment_code.value }}" {% endif %}>
                                </div>
                                <div class="text-danger">{{ form.enrollment_code.errors }}</div>
                            </div>

                            {% for hidden_field in form.hidden_fields %}
                                {{ hidden_field }}
                            {% endfor %}

                            <button type="submit" class="btn btn-warning float-right">Enroll</button>
                        </form>

                    </div>

                    <div class="card-footer">
                        {% if form.next.value %}
                            <div class="text-muted">If you already enrolled earlier then go here to
                                <a href="{% url 'open_choice_polls:voter-sign-in' %}?next={{ form.next.value }}">sign
                                    in</a></div>
                        {% else %}
                            <div class="text-muted">If you already enrolled earlier then go here to
                                <a href="{% url 'open_choice_polls:voter-sign-in' %}">sign in</a></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

open_choice_polls/templates/open_choice_polls/voter_sign_in.html
{% extends "open_choice_polls/base.html" %}
{% load i18n static %}

{% block title %}
    {# Translators: Title onSign In Page #}
    {% trans "Sign In" as title %}
    {{ title }}
{% endblock %}

{% block content %}

    <div class="container">

        {#       START Error#}
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col">
                    <div class="card border-dark mb-3">
                        <div class="card-body">
                            <p class="text-danger">
                                You are authenticated as <strong>{{ user.get_username }}</strong>, but are not
                                authorized
                                to access this page. Would you like to login to a different account?
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        {% if form.errors or form.non_field_errors %}
            <div class="row">
                <div class="col">
                    <div class="card border-secondary mb-3">

                        <div class="card-body">

                            Errors (if any..) #TODO

                            {% if form.errors and not form.non_field_errors %}
                                <p class="errornote">
                                    {% if form.errors.items|length == 1 %}
                                        {% trans "Please correct the error below." %}{% else %}
                                        {% trans "Please correct the errors below." %}{% endif %}
                                </p>
                                {#                            {{ form.errors }}#}
                            {% endif %}

                            {% if form.non_field_errors %}
                                {% for error in form.non_field_errors %}
                                    <p class="errornote">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        {#       END Error#}

        <div class="row">
            <div class="col">

                <div class="card border-dark mb-3">

                    <div class="card-header text-white bg-primary">
                        <h5>Sign In (if you enrolled earlier)</h5>
                    </div>
                    <div class="card-body">

                        <form action="{% url 'open_choice_polls:voter-sign-in' %}" method="post" id="login-form">
                            {% csrf_token %}

                            {% if form.username.value %}
                                <div class="form-group row">
                                    <label for="id_username"
                                           class="col-sm-3 col-form-label">{{ form.username.label }}</label>
                                    <div class="col-sm-9">
                                        <input type="text"
                                               class="form-control-plaintext"
                                               id="id_username"
                                               name="username"
                                               placeholder="e.g. anon12345"
                                               readonly
                                               value="{{ form.username.value }}">
                                    </div>
                                    <div class="text-danger">{{ form.username.errors }}</div>
                                </div>

                                <div class="form-group row">
                                    <label for="id_password"
                                           class="col-sm-3 col-form-label">{{ form.password.label }}</label>
                                    <div class="col-sm-9">
                                        <input type="password"
                                               class="form-control"
                                               id="id_password"
                                               name="password"
                                               placeholder="Password - not the enrollment code!"
                                               autofocus
                                               required>
                                    </div>
                                    <div class="text-danger">{{ form.password.errors }}</div>
                                </div>
                            {% else %}
                                <div class="form-group row">
                                    <label for="id_username"
                                           class="col-sm-3 col-form-label">{{ form.username.label }}</label>
                                    <div class="col-sm-9">
                                        <input type="text"
                                               class="form-control"
                                               id="id_username"
                                               name="username"
                                               placeholder="e.g. anon12345"
                                               autofocus
                                               required>
                                    </div>
                                    <div class="text-danger">{{ form.username.errors }}</div>
                                </div>

                                <div class="form-group row">
                                    <label for="id_password"
                                           class="col-sm-3 col-form-label">{{ form.password.label }}</label>
                                    <div class="col-sm-9">
                                        <input type="password"
                                               class="form-control"
                                               id="id_password"
                                               name="password"
                                               placeholder="Password - not the enrollment code!"
                                               required>
                                    </div>
                                    <div class="text-danger">{{ form.password.errors }}</div>
                                </div>
                            {% endif %}

                            {% for hidden_field in form.hidden_fields %}
                                {{ hidden_field }}
                            {% endfor %}

                            <button type="submit" class="btn btn-primary float-right">Sign In</button>
                        </form>

                    </div>

                    <div class="card-footer">
                        <div class="text-muted">If you don't have a password then go here to
                            <a href="{% url 'open_choice_polls:voter-enroll' %}">activate an enrollment code</a>
                        </div>
                    </div>

                </div>


            </div>
        </div>


    </div>
{% endblock %}